#!/usr/bin/perl -w

use strict;
use lib $ENV{'AARON'};
use lib $ENV{'PERL_LIB'};

use AaronTools::Geometry;

my $file = $ARGV[0];

unless($file) {
    die("A file name must be provided\n");
}

my $geo = new AaronTools::Geometry();

$geo->{name} = $file;

$geo->read_geometry($file) or die ("File may be damaged, cannot read geometry\n");

$geo->printXYZ();
    



