#!/usr/bin/perl -w
use strict;

while (<>) {
  if($_ =~ /^(\d+)$/) {
    my $numatoms = $1;
    my $line = <>;
    my $structure;
    my @geom;
    if($line =~ /^(.*): ([R|S])\.(\S+) optimized geometry/) {
      $cat = $1;
      $stereo = $2;
      $structure = $3;
      $cat =~ s/ \(R = Me\)/Me/g;
      $structure =~ s/bp/ts/g;
    }
    foreach (0..$numatoms-1) {
      my $line = <>;
      push(@geom, $line);
    }
    print "$structure\n";
    open FILE, ">$structure.xyz" or die "Can't!";
    print FILE "$numatoms\n";
    print FILE "F:19-23;2-15 C:23 L:24-$numatoms; K:1,2\n";
    foreach (@geom) {
     print FILE "$_";
    }
  }
  
}

