#BSUB -J test
#BSUB -o test.job.%J
#BSUB -L /bin/bash
#BSUB -W 12:00
#BSUB -M 2700
#BSUB -R 'rusage[mem=2700]'
#BSUB -n 20
#BSUB -R 'span[ptile=20]'
export g09root=/software/lms/g09_D01
. $g09root/g09/bsd/g09.profile
trap "rm -r $SCRATCH/$LSB_JOBID" 0 1 2 3 9 13 14 15
mkdir $SCRATCH/$LSB_JOBID
cd $SCRATCH/$LSB_JOBID
echo -P- 20 > Default.Route
echo -M- 4000000000 >> Default.Route
module purge
env
cp $LS_SUBCWD/*.chk .
g09  < $LS_SUBCWD/test.com  > $LS_SUBCWD/test.log
cp *.chk $LS_SUBCWD/
exit

