#PBS -S /bin/bash
#PBS -q wheeler_q
#PBS -N test
#PBS -m n
#PBS -l nodes=1:ppn=20
#PBS -l walltime=12:00:00
#PBS -l mem=40gb

module load gaussian/09-Intel-SSE4_2
export GAUSS_SCRDIR=/lscratch/$USER/$PBS_JOBID
mkdir -p $GAUSS_SCRDIR
cd $GAUSS_SCRDIR
cp $PBS_O_WORKDIR/test.com .
cp $PBS_O_WORKDIR/*.chk .
. $g09root/g09/bsd/g09.profile
g09 -m="30GB" -p=20 test.com $PBS_O_WORKDIR/test.log
cp *.chk $PBS_O_WORKDIR/.
cd $PBS_O_WORKDIR
rm -rf $GAUSS_SCRDIR
exit

